apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flowops-model-alerts
  labels:
    app: flowops
    component: monitoring
spec:
  groups:
  - name: model-performance
    interval: 30s
    rules:
    # Model availability alerts
    - alert: ModelServingDown
      expr: up{job="model-serving"} == 0
      for: 1m
      labels:
        severity: critical
        component: model-serving
      annotations:
        summary: "Model serving endpoint is down"
        description: "Model serving endpoint {{ $labels.instance }} has been down for more than 1 minute."
        runbook_url: "https://docs.flowops.io/runbooks/model-serving-down"
    
    - alert: ModelHighErrorRate
      expr: |
        (
          sum(rate(model_predictions_total{status="error"}[5m])) /
          sum(rate(model_predictions_total[5m]))
        ) > 0.05
      for: 5m
      labels:
        severity: warning
        component: model-serving
      annotations:
        summary: "High error rate in model predictions"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has error rate of {{ $value | humanizePercentage }} for the last 5 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/high-error-rate"
    
    - alert: ModelCriticalErrorRate
      expr: |
        (
          sum(rate(model_predictions_total{status="error"}[5m])) /
          sum(rate(model_predictions_total[5m]))
        ) > 0.10
      for: 2m
      labels:
        severity: critical
        component: model-serving
      annotations:
        summary: "Critical error rate in model predictions"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has critical error rate of {{ $value | humanizePercentage }} for the last 2 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/critical-error-rate"
    
    # Latency alerts
    - alert: ModelHighLatency
      expr: |
        histogram_quantile(0.95,
          sum(rate(model_prediction_duration_seconds_bucket[5m])) by (le, model, version)
        ) > 0.5
      for: 5m
      labels:
        severity: warning
        component: model-serving
      annotations:
        summary: "High latency in model predictions"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has 95th percentile latency of {{ $value | humanizeDuration }} for the last 5 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/high-latency"
    
    - alert: ModelCriticalLatency
      expr: |
        histogram_quantile(0.95,
          sum(rate(model_prediction_duration_seconds_bucket[5m])) by (le, model, version)
        ) > 1.0
      for: 2m
      labels:
        severity: critical
        component: model-serving
      annotations:
        summary: "Critical latency in model predictions"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has 95th percentile latency of {{ $value | humanizeDuration }} for the last 2 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/critical-latency"
    
    # Throughput alerts
    - alert: ModelLowThroughput
      expr: |
        sum(rate(model_predictions_total[5m])) by (model, version) < 1
      for: 10m
      labels:
        severity: warning
        component: model-serving
      annotations:
        summary: "Low throughput in model predictions"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has low throughput of {{ $value | humanize }} requests/sec for the last 10 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/low-throughput"
    
    # Resource utilization alerts
    - alert: ModelHighCPUUsage
      expr: |
        (
          sum(rate(container_cpu_usage_seconds_total{pod=~".*model-serving.*"}[5m])) by (pod) /
          sum(container_spec_cpu_quota{pod=~".*model-serving.*"} / container_spec_cpu_period{pod=~".*model-serving.*"}) by (pod)
        ) > 0.8
      for: 10m
      labels:
        severity: warning
        component: model-serving
      annotations:
        summary: "High CPU usage in model serving pods"
        description: "Pod {{ $labels.pod }} has high CPU usage of {{ $value | humanizePercentage }} for the last 10 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/high-cpu-usage"
    
    - alert: ModelHighMemoryUsage
      expr: |
        (
          sum(container_memory_working_set_bytes{pod=~".*model-serving.*"}) by (pod) /
          sum(container_spec_memory_limit_bytes{pod=~".*model-serving.*"}) by (pod)
        ) > 0.8
      for: 10m
      labels:
        severity: warning
        component: model-serving
      annotations:
        summary: "High memory usage in model serving pods"
        description: "Pod {{ $labels.pod }} has high memory usage of {{ $value | humanizePercentage }} for the last 10 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/high-memory-usage"
    
    # Model quality alerts (requires custom metrics from model)
    - alert: ModelAccuracyDrift
      expr: |
        model_accuracy_score < 0.85
      for: 15m
      labels:
        severity: warning
        component: model-quality
      annotations:
        summary: "Model accuracy below threshold"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has accuracy of {{ $value | humanizePercentage }} which is below the 85% threshold."
        runbook_url: "https://docs.flowops.io/runbooks/accuracy-drift"
    
    - alert: ModelDataDrift
      expr: |
        model_data_drift_score > 0.3
      for: 30m
      labels:
        severity: warning
        component: model-quality
      annotations:
        summary: "Data drift detected in model inputs"
        description: "Model {{ $labels.model }} version {{ $labels.version }} has data drift score of {{ $value }} which indicates significant drift in input data distribution."
        runbook_url: "https://docs.flowops.io/runbooks/data-drift"

  - name: mlflow
    interval: 30s
    rules:
    # MLflow server alerts
    - alert: MLflowServerDown
      expr: up{job="mlflow"} == 0
      for: 2m
      labels:
        severity: critical
        component: mlflow
      annotations:
        summary: "MLflow server is down"
        description: "MLflow server {{ $labels.instance }} has been down for more than 2 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/mlflow-down"
    
    - alert: MLflowHighLatency
      expr: |
        histogram_quantile(0.95,
          sum(rate(mlflow_request_duration_seconds_bucket[5m])) by (le)
        ) > 5.0
      for: 5m
      labels:
        severity: warning
        component: mlflow
      annotations:
        summary: "High latency in MLflow requests"
        description: "MLflow server has 95th percentile latency of {{ $value | humanizeDuration }} for the last 5 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/mlflow-high-latency"
    
    - alert: MLflowDatabaseConnectionFailed
      expr: |
        mlflow_database_connection_errors_total > 0
      for: 1m
      labels:
        severity: critical
        component: mlflow
      annotations:
        summary: "MLflow database connection failed"
        description: "MLflow server cannot connect to the database. {{ $value }} connection errors in the last minute."
        runbook_url: "https://docs.flowops.io/runbooks/mlflow-db-connection"

  - name: infrastructure
    interval: 30s
    rules:
    # Kubernetes cluster alerts
    - alert: HighPodCrashRate
      expr: |
        rate(kube_pod_container_status_restarts_total{pod=~".*flowops.*"}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "High pod crash rate detected"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has a restart rate of {{ $value }} per second."
        runbook_url: "https://docs.flowops.io/runbooks/pod-crashes"
    
    - alert: PodStuckInPendingState
      expr: |
        sum by (namespace, pod) (kube_pod_status_phase{phase="Pending", pod=~".*flowops.*"}) > 0
      for: 10m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "Pod stuck in pending state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in pending state for more than 10 minutes."
        runbook_url: "https://docs.flowops.io/runbooks/pod-pending"
    
    # Storage alerts
    - alert: PersistentVolumeClaimPendingState
      expr: |
        kube_persistentvolumeclaim_status_phase{phase="Pending"} > 0
      for: 5m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "PVC in pending state"
        description: "PersistentVolumeClaim {{ $labels.persistentvolumeclaim }} in namespace {{ $labels.namespace }} is in pending state."
        runbook_url: "https://docs.flowops.io/runbooks/pvc-pending"
    
    - alert: PersistentVolumeUsageHigh
      expr: |
        (
          kubelet_volume_stats_used_bytes /
          kubelet_volume_stats_capacity_bytes
        ) > 0.85
      for: 10m
      labels:
        severity: warning
        component: infrastructure
      annotations:
        summary: "High persistent volume usage"
        description: "PersistentVolume {{ $labels.persistentvolume }} usage is {{ $value | humanizePercentage }}."
        runbook_url: "https://docs.flowops.io/runbooks/high-pv-usage"